/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ['./App.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],

    presets: [require('nativewind/preset')],
    theme: {
        extend: {
            colors: {
                primary: 'rgb(var(--color-primary) / <alpha-value>)',
                surfaceTint: 'rgb(var(--color-surfaceTint) / <alpha-value>)',
                onPrimary: 'rgb(var(--color-onPrimary) / <alpha-value>)',
                primaryContainer: 'rgb(var(--color-primaryContainer) / <alpha-value>)',
                onPrimaryContainer: 'rgb(var(--color-onPrimaryContainer) / <alpha-value>)',
                secondary: 'rgb(var(--color-secondary) / <alpha-value>)',
                onSecondary: 'rgb(var(--color-onSecondary) / <alpha-value>)',
                secondaryContainer: 'rgb(var(--color-secondaryContainer) / <alpha-value>)',
                onSecondaryContainer: 'rgb(var(--color-onSecondaryContainer) / <alpha-value>)',
                tertiary: 'rgb(var(--color-tertiary) / <alpha-value>)',
                onTertiary: 'rgb(var(--color-onTertiary) / <alpha-value>)',
                tertiaryContainer: 'rgb(var(--color-tertiaryContainer) / <alpha-value>)',
                onTertiaryContainer: 'rgb(var(--color-onTertiaryContainer) / <alpha-value>)',
                error: 'rgb(var(--color-error) / <alpha-value>)',
                onError: 'rgb(var(--color-onError) / <alpha-value>)',
                errorContainer: 'rgb(var(--color-errorContainer) / <alpha-value>)',
                onErrorContainer: 'rgb(var(--color-onErrorContainer) / <alpha-value>)',
                background: 'rgb(var(--color-background) / <alpha-value>)',
                onBackground: 'rgb(var(--color-onBackground) / <alpha-value>)',
                surface: 'rgb(var(--color-surface) / <alpha-value>)',
                onSurface: 'rgb(var(--color-onSurface) / <alpha-value>)',
                surfaceVariant: 'rgb(var(--color-surfaceVariant) / <alpha-value>)',
                onSurfaceVariant: 'rgb(var(--color-onSurfaceVariant) / <alpha-value>)',
                outline: 'rgb(var(--color-outline) / <alpha-value>)',
                outlineVariant: 'rgb(var(--color-outlineVariant) / <alpha-value>)',
                shadow: 'rgb(var(--color-shadow) / <alpha-value>)',
                scrim: 'rgb(var(--color-scrim) / <alpha-value>)',
                inverseSurface: 'rgb(var(--color-inverseSurface) / <alpha-value>)',
                inverseOnSurface: 'rgb(var(--color-inverseOnSurface) / <alpha-value>)',
                inversePrimary: 'rgb(var(--color-inversePrimary) / <alpha-value>)',
                primaryFixed: 'rgb(var(--color-primaryFixed) / <alpha-value>)',
                onPrimaryFixed: 'rgb(var(--color-onPrimaryFixed) / <alpha-value>)',
                primaryFixedDim: 'rgb(var(--color-primaryFixedDim) / <alpha-value>)',
                onPrimaryFixedVariant: 'rgb(var(--color-onPrimaryFixedVariant) / <alpha-value>)',
                secondaryFixed: 'rgb(var(--color-secondaryFixed) / <alpha-value>)',
                onSecondaryFixed: 'rgb(var(--color-onSecondaryFixed) / <alpha-value>)',
                secondaryFixedDim: 'rgb(var(--color-secondaryFixedDim) / <alpha-value>)',
                onSecondaryFixedVariant: 'rgb(var(--color-onSecondaryFixedVariant) / <alpha-value>)',
                tertiaryFixed: 'rgb(var(--color-tertiaryFixed) / <alpha-value>)',
                onTertiaryFixed: 'rgb(var(--color-onTertiaryFixed) / <alpha-value>)',
                tertiaryFixedDim: 'rgb(var(--color-tertiaryFixedDim) / <alpha-value>)',
                onTertiaryFixedVariant: 'rgb(var(--color-onTertiaryFixedVariant) / <alpha-value>)',
                surfaceDim: 'rgb(var(--color-surfaceDim) / <alpha-value>)',
                surfaceBright: 'rgb(var(--color-surfaceBright) / <alpha-value>)',
                surfaceContainerLowest: 'rgb(var(--color-surfaceContainerLowest) / <alpha-value>)',
                surfaceContainerLow: 'rgb(var(--color-surfaceContainerLow) / <alpha-value>)',
                surfaceContainer: 'rgb(var(--color-surfaceContainer) / <alpha-value>)',
                surfaceContainerHigh: 'rgb(var(--color-surfaceContainerHigh) / <alpha-value>)',
                surfaceContainerHighest: 'rgb(var(--color-surfaceContainerHighest) / <alpha-value>)',
            },
        },
    },
    plugins: [],
};
